### ISSUE TITLE
Project is still alive ?

### ISSUE THREAD

**Issue by unix85** [binstreamio/tvbus.android#10]
Hello ...
Maybe is just one issue. The project is still ON ?
I tried to contact someone from the team but ... :(
Nobody answer on email. Is maybe are some free days ?
I hope that the people are healthy. I\m concerning just about this ...

**Comment by kovacsconstantin** [comment]
Is more than one year since I have no answer from the team. We are customers and we paid for software. Problem is that all go even now to them and we need support to fix this.  We are customers from abroad and we PAID for that. 
Anyone can help us ?

**Comment by marcel299** [comment]
Hello kovacsconstantin, have you received an answer about the system?
