### ISSUE TITLE
不能播放

### ISSUE THREAD

**Issue by sunfengqi8023** [binstreamio/tvbus.android#3]
tvbus不能播放，换成其他tvbus也不能播放

**Comment by binstreamio** [comment]
能发下tvbus地址吗？现在网上很多地址都是失效的。

**Comment by jeff-kl** [comment]
CCTV1,tvbus://1R8Rw3uqyfdkci7b9VWm7N17ynqv259h1Bo7i2uyi9bmq513uXCCTV2,tvbus://12MGYHm2fp2wtTjiGpDsbD1odpShZDSn5ub2y74ok1HX5WB6wk
麻烦试试这个

**Comment by binstreamio** [comment]
上面的频道有些限制，下面的两个频道试试看
tvbus://1TqsjW9qwS2AnAnTnE9wYYhjM2hCJL9W7QRQsXbHtR2gcVU2uo
tvbus://12ttiFPWgoNneGH97HRN7Gu2Qjv6N3yNs6Q5DbVzqUAdC4d1fVY
