### ISSUE TITLE
SopStreamer Cannot Use?

### ISSUE THREAD

**Issue by hellfire1980** [binstreamio/tvbus.android#5]
Is sopstreamer cannot use?

**Comment by binstreamio** [comment]
sopstreamer's server was blocked because of users' unauthorized content publishing. We are trying to bring the server back.

**Comment by cooliobr** [comment]
So, i can use my HLS server instead of sopstreamer?

**Comment by binstreamio** [comment]
No. Only sopstreamer can split stream data into blocks and transfer by p2p
